spring.datasource.url=${STORAGE_DB_URL:jdbc:postgresql://localhost:5435/storagedb}
spring.datasource.username=${STORAGE_DB_USER:pguser}
spring.datasource.password=${STORAGE_DB_PASSWORD:pgpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

s3.endpoint=${S3_ENDPOINT:http://localhost:9000}
s3.access-key=${S3_ACCESS_KEY:s3admin}
s3.secret-key=${S3_SECRET_KEY:s3admin}
s3.region=${S3_REGION:us-east-1}

storage.staging.bucket=${STAGING_BUCKET:resources-staging}
storage.staging.path=/files
storage.permanent.bucket=${PERMANENT_BUCKET:resources-permanent}
storage.permanent.path=/files
